"""Hand-written, hand-labeled product reviews for Lab 6 (fictional retailer, fictional customers).
topic: the MAIN issue the review is about. sentiment: Positive / Negative / Mixed.
Some are deliberately hard (sarcasm, two topics, non-English, very short) -- see `hard` flag."""
import pandas as pd, os
R = [
# (product_id, stars, text, topic, sentiment, hard)
(112, 5, "Broke these boots in over one weekend and did 14 miles on day three with zero blisters. Solid ankle support.", "Quality", "Positive", 0),
(112, 2, "Ordered my usual 10 and they were painfully tight. Had to send them back and wait another week for an 11.", "Fit/Sizing", "Negative", 0),
(113, 4, "Waterproofing held up through a full day of rain. Runs about half a size small though.", "Quality", "Mixed", 1),
(114, 5, "Light, grippy, and my feet stayed dry on wet rock. Best trail shoe I've owned.", "Quality", "Positive", 0),
(114, 1, "Sole started peeling away from the toe after six weeks of easy trail running.", "Quality", "Negative", 0),
(115, 3, "Comfortable around camp. Nothing special for forty bucks.", "Value", "Mixed", 0),
(116, 2, "Size chart says true to size. It is not. Go up a full size.", "Fit/Sizing", "Negative", 0),
(117, 5, "Kept my toes warm at minus 15 while ice fishing. Worth every penny.", "Quality", "Positive", 0),
(117, 4, "Warm and well made but heavy. Fits true to size with thick socks.", "Quality", "Positive", 0),
(118, 5, "Softest merino I've tried and it doesn't itch at all. Wore it four days straight on a hut trip and it didn't smell.", "Quality", "Positive", 0),
(118, 2, "Shrunk a full size after one wash on cold. Followed the label.", "Quality", "Negative", 0),
(119, 3, "Good fabric, but the legs are cut really long. I'm 5'6\" and had to hem them.", "Fit/Sizing", "Mixed", 0),
(120, 5, "Stayed dry in a sideways downpour on the ridge. Pit zips are a nice touch.", "Quality", "Positive", 0),
(120, 1, "$249 for a jacket that wetted out in the first real storm. Absolutely not worth it.", "Value", "Negative", 1),
(120, 4, "Great shell. Took 11 days to arrive when checkout said 3-5.", "Shipping", "Mixed", 1),
(121, 5, "Packs into its own pocket and is shockingly warm for the weight.", "Quality", "Positive", 0),
(121, 2, "Feathers leaking out of the seams from day one. Customer service did send a replacement quickly.", "Quality", "Mixed", 1),
(122, 4, "Cozy, true to size, and the zipper feels sturdy.", "Quality", "Positive", 0),
(123, 3, "Fits fine but the fabric pills where my pack straps rub.", "Quality", "Mixed", 0),
(123, 5, "Perfect length, stretchy, and the pockets actually hold a phone.", "Fit/Sizing", "Positive", 0),
(124, 5, "UPF hoodie that doesn't feel like wearing a trash bag in the heat. Bought two more.", "Quality", "Positive", 0),
(125, 4, "Great socks. A little pricey for three pairs but they last.", "Value", "Positive", 0),
(125, 1, "Holes in both heels after a month. Cheap socks at an expensive price.", "Value", "Negative", 0),
(101, 5, "Set up in under five minutes in the dark. Stayed bone dry in an overnight thunderstorm.", "Quality", "Positive", 0),
(101, 2, "One of the poles arrived cracked. Emailed support three times, no reply after two weeks.", "Customer Service", "Negative", 1),
(102, 4, "Plenty of room for two adults and two kids. A bit heavy for backpacking but fine for car camping.", "Quality", "Positive", 0),
(103, 5, "Under two pounds and actually livable. My new go-to for solo trips.", "Quality", "Positive", 0),
(103, 2, "Condensation city. Woke up with the inside of the fly dripping on my bag every night.", "Quality", "Negative", 0),
(104, 3, "Huge and sturdy but the box was crushed and one stake bag was missing.", "Shipping", "Mixed", 1),
(105, 5, "Simple, light, and pitches a dozen ways. Great value compared to the big brands.", "Value", "Positive", 0),
(106, 5, "Just the right size for day hikes. Hip belt pockets are genius.", "Quality", "Positive", 0),
(107, 4, "Comfortable with 30 lbs. Wish the rain cover were included at this price.", "Value", "Mixed", 1),
(107, 1, "Shoulder strap buckle snapped on the second trip. Mid-hike. Great.", "Quality", "Negative", 1),
(108, 5, "Carried 45 lbs for five days in the Winds and my shoulders were fine. Torso adjustment is easy.", "Fit/Sizing", "Positive", 1),
(108, 2, "Torso length runs short. Even at max setting it sits too high on my back.", "Fit/Sizing", "Negative", 0),
(109, 4, "Fits a laptop and gym clothes. Looks sharp for the price.", "Value", "Positive", 0),
(110, 5, "Doesn't bounce at all on runs. Holds two soft flasks and a jacket.", "Quality", "Positive", 0),
(111, 5, "My 7 year old insists on wearing it everywhere, including to bed.", "Quality", "Positive", 1),
(126, 5, "Nests perfectly with the canister stove inside. Light and boils fast.", "Quality", "Positive", 0),
(127, 2, "Igniter stopped working on the second outing. Had to carry a lighter anyway.", "Quality", "Negative", 0),
(128, 4, "Keeps coffee hot for hours. Lid leaks slightly if tipped.", "Quality", "Mixed", 0),
(129, 5, "Filtered stream water all week and nobody got sick. Easy to backflush.", "Quality", "Positive", 0),
(129, 3, "Works, but the flow rate is painfully slow after a few days.", "Quality", "Mixed", 0),
(130, 4, "Cheap, light, does the job.", "Value", "Positive", 0),
(131, 3, "It's a bucket that folds. Fine.", "Quality", "Mixed", 1),
(132, 5, "Bright, rechargeable, and the red mode is great for not blinding your tent mate.", "Quality", "Positive", 0),
(132, 1, "Battery died after 90 minutes on high. Advertised 4 hours.", "Quality", "Negative", 0),
(133, 4, "Sturdy poles and the flick locks are easy with gloves on.", "Quality", "Positive", 0),
(134, 5, "Slept warm at 25F. Zipper doesn't snag.", "Quality", "Positive", 0),
(134, 2, "Rated 20F but I was shivering at 35F.", "Quality", "Negative", 0),
(135, 4, "Comfy for side sleepers, but it crinkles loudly every time you move.", "Quality", "Mixed", 0),
(136, 5, "Kept my camera dry on a capsized kayak day. Enough said.", "Quality", "Positive", 0),
(137, 3, "Decent kit but half of it is bandaids. Overpriced for what's in it.", "Value", "Negative", 1),
(138, 5, "Most comfortable camp chair I've sat in and it packs small.", "Quality", "Positive", 0),
(138, 2, "Seat fabric tore at the seam the first time my (average-sized) husband sat in it.", "Quality", "Negative", 0),
# shipping / service / order experience
(107, 1, "Package sat in 'label created' for nine days. Finally showed up two days after my trip.", "Shipping", "Negative", 0),
(120, 5, "Ordered Tuesday, arrived Thursday. Packaging was all recyclable too.", "Shipping", "Positive", 0),
(113, 2, "Tracking said delivered. It was not delivered. Took a week of calls to get a reship.", "Shipping", "Negative", 1),
(101, 5, "Tent was defective but support sent a new one before I even shipped the old one back. That's how you keep a customer.", "Customer Service", "Positive", 1),
(118, 5, "The chat agent helped me pick the right size and was spot on.", "Customer Service", "Positive", 0),
(114, 1, "Tried to return unworn shoes on day 31 of a 30 day window and they refused. One day.", "Customer Service", "Negative", 0),
(121, 4, "Arrived fast but the box had clearly been opened and re-taped.", "Shipping", "Mixed", 0),
(126, 2, "Received the wrong item, a mug instead of a pot set. Return label took 5 days to arrive by email.", "Shipping", "Negative", 1),
(133, 5, "Customer service replaced a bent pole section for free, no questions asked, two years after purchase.", "Customer Service", "Positive", 0),
(134, 1, "I've been on hold for 40 minutes to ask about a warranty claim. Still waiting as I write this.", "Customer Service", "Negative", 0),
(122, 3, "Nice fleece, but shipping to Ireland cost almost as much as the fleece.", "Value", "Mixed", 1),
(112, 4, "Delivered to Germany in four days, faster than I expected from a US shop.", "Shipping", "Positive", 0),
(108, 3, "Great pack but customs fees on delivery to the UK were a nasty surprise nobody mentioned.", "Shipping", "Mixed", 1),
(132, 5, "Return was painless, refund posted within two days.", "Customer Service", "Positive", 0),
# value
(104, 2, "$529 and the zippers feel like they came off a $40 tent.", "Value", "Negative", 1),
(109, 5, "Half the price of the brand-name commuter bags and honestly better built.", "Value", "Positive", 0),
(117, 3, "Good boot, but I found it $60 cheaper at another store the next day.", "Value", "Mixed", 0),
(124, 5, "Bought it on the 30% off sale. Would have happily paid full price.", "Value", "Positive", 1),
(130, 2, "Twenty dollars for a spoon, fork and knife that bend if you look at them.", "Value", "Negative", 0),
(119, 4, "Pricey for long underwear, but you get what you pay for.", "Value", "Positive", 1),
(135, 4, "Not the lightest pad out there but a great deal on sale.", "Value", "Positive", 0),
# sizing
(116, 5, "Fits perfectly. Ordered my normal size and they were comfortable out of the box.", "Fit/Sizing", "Positive", 0),
(113, 3, "Great boot if you have narrow feet. I don't.", "Fit/Sizing", "Mixed", 1),
(122, 2, "The 'medium' fits like an XL. Everything about this is huge.", "Fit/Sizing", "Negative", 0),
(120, 4, "Sized up so I could layer a puffy underneath and it's perfect.", "Fit/Sizing", "Positive", 0),
(123, 2, "Waist runs two inches smaller than the size chart.", "Fit/Sizing", "Negative", 0),
(106, 4, "Fits my small frame better than most packs, which usually sit too low.", "Fit/Sizing", "Positive", 0),
(111, 2, "Straps don't adjust short enough for a 5 year old despite the listing.", "Fit/Sizing", "Negative", 0),
(124, 3, "Sleeves are a little short on me (long arms), otherwise great.", "Fit/Sizing", "Mixed", 0),
# hard / tricky
(120, 1, "Oh great, another 'waterproof' jacket. Loved standing in the rain getting soaked. Ten out of ten.", "Quality", "Negative", 1),
(127, 5, "Well, it certainly boiled the water. Eventually. After I lit it with a match.", "Quality", "Negative", 1),
(110, 4, "ok", "Quality", "Positive", 1),
(131, 5, "👍👍", "Quality", "Positive", 1),
(112, 2, "Die Stiefel sind bequem, aber nach zwei Monaten löst sich die Sohle.", "Quality", "Negative", 1),
(121, 5, "Très chaude et légère, parfaite pour la randonnée en hiver.", "Quality", "Positive", 1),
(102, 3, "Returned it. Not because it's bad, my family just decided we hate camping.", "Quality", "Mixed", 1),
(129, 1, "Five stars for the filter, one star because it arrived three weeks late for my trip.", "Shipping", "Mixed", 1),
(118, 4, "Love it. Would be 5 stars but the color in person is more orange than red.", "Quality", "Positive", 1),
(125, 5, "Bought these for my dad. He says they're 'fine', which from him is the highest praise possible.", "Quality", "Positive", 1),
(105, 2, "Great product, terrible instructions. Took 40 minutes and a YouTube video to pitch.", "Quality", "Mixed", 1),
(136, 4, "Does what it says. Not much more to say about a bag.", "Quality", "Positive", 0),
(134, 5, "Your warehouse team deserves a raise, the bag arrived packed like it was a museum piece.", "Shipping", "Positive", 1),
(138, 1, "Please call me back about order 500213, nobody has answered my three emails.", "Customer Service", "Negative", 1),
(114, 3, "Grippy on rock, slippery on wet roots. Comfort is great, durability TBD.", "Quality", "Mixed", 0),
(107, 5, "Returned my old pack from another brand and bought this. No regrets.", "Quality", "Positive", 1),
(126, 4, "Arrived dented, but it's a pot, it'll get dented anyway. Works great.", "Shipping", "Mixed", 1),
(128, 2, "Keeps drinks hot but the paint chipped off in a week.", "Quality", "Mixed", 1),
(101, 4, "Good tent. Instructions say 'easy one-person setup'. That person must have four arms.", "Quality", "Mixed", 1),
(119, 5, "My partner stole mine so I had to order a second pair.", "Quality", "Positive", 1),
(137, 5, "Used it on a real injury on the trail. Everything we needed was in there.", "Quality", "Positive", 0),
(132, 3, "Bright enough. Headband gets sweaty.", "Quality", "Mixed", 0),
(103, 4, "Great tent. The $30 footprint should really be included though.", "Value", "Mixed", 1),
(117, 1, "Arrived in the wrong size AND the wrong color. Impressive.", "Shipping", "Negative", 1),
(135, 5, "Finally slept through the night on the ground. My back thanks you.", "Quality", "Positive", 0),
(116, 4, "Very grippy, a bit stiff at first. Softened up after a couple of weeks.", "Quality", "Positive", 0),
(109, 2, "Zipper broke within a month and the replacement process wants me to pay shipping both ways.", "Customer Service", "Negative", 1),
(115, 5, "Wore them in the shower at the campground and they dried in minutes.", "Quality", "Positive", 0),
(106, 3, "Nice pack, but the hydration sleeve doesn't fit a 3L bladder like the listing says.", "Quality", "Mixed", 0),
(133, 2, "One lock slips under weight. Support says it's 'user error'.", "Customer Service", "Negative", 1),
]
df = pd.DataFrame(R, columns=["product_id", "stars", "review_text", "human_topic", "human_sentiment", "hard"])
df.insert(0, "review_id", range(1, len(df) + 1))
here = os.path.dirname(__file__)
df.drop(columns="hard").to_csv(os.path.join(here, "..", "data", "reviews.csv"), index=False)
df[["review_id", "hard"]].to_csv(os.path.join(here, "reviews_hard_flags.csv"), index=False)
print(df.shape); print(df.human_topic.value_counts()); print(df.human_sentiment.value_counts()); print("hard", df.hard.sum())
